#version 460
#extension GL_EXT_shader_atomic_float : enable

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;
layout(binding = 0, set = 0) buffer Counter { float energy; };
layout(binding = 1, rgba32f) uniform readonly image2D imageSrc;

void main() {
    ivec2 loc = ivec2(gl_GlobalInvocationID.xy);
    vec4 s = imageLoad(imageSrc, loc * 4);
    float toAdd = dot(vec3(1), s.xyz / s.w);
    atomicAdd(energy, toAdd);
}
