#version 460

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;
layout(binding = 0, rgba32f) uniform writeonly image2D image;

layout (push_constant) uniform PushConstant {
    float time;
};

void main() {
    ivec2 loc = ivec2(gl_GlobalInvocationID.xy);
    float c = float(((loc.x+int(time*40))/32 + loc.y/32) % 2);
    vec4 color = vec4(0,c,c, 1);
    imageStore(image, loc, color);
}
